apiVersion: v1
kind: ServiceAccount
metadata:
  name: ticketing-api
  namespace: ticketing-system
  labels:
    app.kubernetes.io/part-of: ticketing-system
    app.kubernetes.io/component: api
automountServiceAccountToken: false
